name: pylide
channels:
  - defaults
dependencies:
  - python=3.12
  - cmake=3.31
  - ninja=1.12.1
  - pip
  - pip:
    - -r requirements.txt

# conda env create -f environment.yml
# conda env update -f environment.yml